# https://www.netlify.com/docs/netlify-toml-reference/

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://vuetensils.netlify.com/*"
  to = "https://vuetensils.austingil.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://vuetensils.netlify.com/*"
  to = "https://vuetensils.austingil.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://vuetensils.stegosource.com/*"
  to = "https://vuetensils.stegosource.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://vuetensils.stegosource.com/*"
  to = "https://vuetensils.stegosource.com/:splat"
  status = 301
  force = true
