export { default as Alert } from "./alert/VtsAlert.vue"
export { default as Drawer } from "./drawer/VtsDrawer.vue"
export { default as Dropdown } from "./dropdown/VtsDropdown.vue"
export { default as Img } from "./img/VtsImg.vue"
export { default as Intersection } from "./intersection/VtsIntersection.vue"
export { default as Modal } from "./modal/VtsModal.vue"
export { default as Tabs } from "./tabs/VtsTabs.vue"
